# Docker compose file

version: "3"

services:
  envoy-logger:
    build: .
    restart: unless-stopped
    environment:
      - ENVOY_LOGGER_CFG_PATH=/etc/envoy_logger/cfg.yaml
    volumes:
      - /local/path/to/envoy_logger:/etc/envoy_logger:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: bridge
